const fs = require('fs');
let content = fs.readFileSync('src/data/translations.ts', 'utf8');

const additions = {
  en: {
    'faq.1.q': 'Is it safe to process PDF files here?',
    'faq.1.a': 'Absolutely. All files are processed locally in your web browser memory using high-performance WebAssembly modules. Not a single byte of your documents is ever uploaded or sent to our servers. Your sensitive business, personal, and confidential records stay entirely secure on your own device.',
    'faq.2.q': 'Is TacoPDF truly 100% free?',
    'faq.2.a': 'Yes, fully free with no hidden fees, no required account registrations, no forced watermarks, and no daily file limit caps. We display a small number of non-intrusive sponsor advertisements (Google AdSense) to help cover static hosting and custom domain overhead costs.',
    'faq.3.q': 'Can I use this toolkit offline without internet?',
    'faq.3.a': 'Yes! Once the web application is loaded in your browser for the first time, all PDF processing logic runs completely on the client side. You can safely disconnect your internet and continue to merge, split, rotate, or protect your PDF files fully offline.',
    'faq.4.q': 'Why does this website show advertisements?',
    'faq.4.a': 'As a public, high-utility tool that values security without charging subscription fees, Google AdSense sponsor ads help fund our basic infrastructure. We optimize ad placement to remain non-disruptive, eye-friendly, and completely separate from your active workspace.',
    'faq.5.q': 'What file formats are supported?',
    'faq.5.a': 'TacoPDF supports any standard PDF document (from version 1.0 to the newest standards), as well as popular image file formats like PNG, JPG, JPEG, and WebP to compile them into professional-grade PDF documents.',
    'workspace.back': 'Back',
    'workspace.tool_config': 'Tool Configurations',
    'workspace.html.title': 'Type or paste HTML / Rich Text:',
    'workspace.html.blank': 'Blank Doc Template',
    'workspace.html.invoice': 'Simple Invoice Template',
    'workspace.html.letter': 'Official Memo Letter',
    'workspace.html.placeholder': 'Enter rich text...',
    'workspace.drop.title': 'Drag and drop files here, or',
    'workspace.drop.browse': 'browse',
    'workspace.drop.support_img': 'Supports PNG, JPG, WebP images.',
    'workspace.drop.support_pdf': 'Supports PDF files.',
    'workspace.drop.security': 'Local WebAssembly client-side execution. Maximum security.',
    'workspace.queue.title': 'Files in Queue',
    'workspace.queue.clear': 'Clear All',
    'workspace.btn.compile': 'Compile PDF Document',
    'workspace.btn.run': 'Run',
    'workspace.progress.processing': 'Processing local Wasm...',
    'workspace.progress.error': 'Error:',
    'workspace.progress.completed': 'Completed:',
    'workspace.rename.title': 'Rename Processed Output:',
    'workspace.rename.placeholder': 'Rename output file',
    'workspace.extract.title': 'Extracted Page Photos',
    'workspace.extract.desc': 'Click the download buttons below to save each page directly as a high-quality photo file (.png) on your device.',
    'workspace.btn.save': 'Save',
    'workspace.btn.download': 'Download PDF',
    'workspace.btn.preview': 'Preview PDF',
    'workspace.btn.another': '← Process Another Document',
    'workspace.custom_name': 'Custom Output Name (Optional)',
    'workspace.custom_name_desc': 'Customize the file name before processing. Or change it later after completion.',
    'workspace.how_to_use': 'How to Use & Tips',
    'workspace.how_to_title': 'How to Use',
    'workspace.tips_title': 'Professional & Security Tips',
    'workspace.preview.live': 'Live client-side PDF preview',
    'workspace.preview.download': 'Download',
    'tool.merge.no_settings': '✨ No settings needed!',
    'tool.merge.desc': 'Simply drop your PDF files on the left. Use the Up (↑) and Down (↓) arrow buttons to arrange them in the exact order you want them merged, then click the action button below!',
    'tool.split.keep': 'Which pages do you want to keep?',
    'tool.split.placeholder': 'e.g. 1-3, 5 (keeps pages 1, 2, 3 and 5)',
    'tool.split.guide': '💡 Easy Guide:',
    'tool.split.guide1': 'Use a dash (1-3) to select pages in a row.',
    'tool.split.guide2': 'Use a comma (1, 4) to separate different pages.',
    'tool.split.guide3': 'Leave this field empty to keep all pages.',
    'tool.rotate.direction': 'Which direction should we turn your pages?',
    'tool.rotate.90': '90° (Turn Right / Sideways)',
    'tool.rotate.180': '180° (Turn Upside Down)',
    'tool.rotate.270': '270° (Turn Left / Sideways)',
    'tool.rotate.apply': 'Apply rotation to:',
    'tool.rotate.all': 'Every single page',
    'tool.rotate.specific': 'Only specific pages',
    'tool.rotate.which': 'Which specific page numbers?',
    'tool.rotate.placeholder': 'e.g. 1, 3, 5 (separate with commas)',
    'tool.protect.choose': 'Choose a Password to Lock your PDF:',
    'tool.protect.placeholder': 'e.g. secret1234 (Keep it simple!)',
    'tool.protect.safe': '🔒 100% Safe & Offline: everything happens privately inside your browser.',
    'tool.protect.important': '⚠️ Important: We cannot recover forgotten passwords. Please write your password down!',
    'tool.unlock.type': 'Type current password to Unlock:',
    'tool.unlock.placeholder': 'Type password here',
    'tool.unlock.note': '💡 Note: Once successfully unlocked, you can open and print your PDF easily without entering a password ever again.',
    'tool.image.size': 'Select Paper Size:',
    'tool.image.a4': 'A4 Size (Most common printer paper)',
    'tool.image.letter': 'Letter Size (Standard office paper)',
    'tool.image.fit': 'Auto Fit (Match picture dimensions)',
    'tool.image.margin': 'Blank Space around edges (Margins):',
    'tool.image.margin_note': '💡 Set this to 0 if you want your pictures to fill the entire page with no white borders.',
    'tool.pdf2img.title': '📸 Extract Page Images',
    'tool.pdf2img.desc': 'No extra settings needed! This tool will instantly convert every page of your PDF into an easy-to-share image (photo) file.',
    'tool.delete.which': 'Which page numbers do you want to delete (remove)?',
    'tool.delete.placeholder': 'e.g. 2, 4 (deletes page 2 and page 4)',
    'tool.delete.example': '💡 Example: Type 2, 4 to wipe out pages 2 and 4. The remaining pages will automatically slide into place without leaving empty gaps!',
    'tool.extract.which': 'Which pages do you want to keep as a new file?',
    'tool.extract.placeholder': 'e.g. 1, 3, 5 (only keeps pages 1, 3, 5)',
    'tool.extract.how': '💡 How it works: Type the pages you want to keep. This creates a brand new, lightweight PDF containing only these pages.',
    'tool.watermark.type': 'Type your Watermark Text:',
    'tool.watermark.placeholder': 'e.g. DRAFT, COPY, CONFIDENTIAL',
    'tool.watermark.size': 'Text Size:',
    'tool.watermark.opacity': 'See-through level (Opacity):',
    'tool.watermark.color': 'Choose Text Color:',
    'tool.watermark.rotation': 'Tilt Angle (Rotation):',
    'tool.watermark.note': '💡 Opacity of 0.2 is very light and faded. 1.0 is solid.',
    'tool.page_num.how': 'How should page numbers look?',
    'tool.page_num.placeholder': 'e.g. Page {n} of {total}',
    'tool.page_num.hint': '💡 Hint: {n} changes to the page number (1, 2, 3), and {total} shows total pages (e.g., Page 1 of 5).',
    'tool.page_num.placement': 'Placement Alignment:',
    'tool.page_num.bottom_center': 'Bottom Middle (Most Popular)',
    'tool.page_num.bottom_right': 'Bottom Right Corner',
    'tool.page_num.bottom_left': 'Bottom Left Corner',
    'tool.page_num.top_center': 'Top Middle',
    'tool.page_num.top_right': 'Top Right Corner'
  },
  id: {
    'faq.1.q': 'Apakah aman memproses file PDF di sini?',
    'faq.1.a': 'Tentu saja. Semua file diproses secara lokal di memori browser Anda menggunakan modul WebAssembly berkinerja tinggi. Tidak ada satu byte pun dari dokumen Anda yang pernah diunggah atau dikirim ke server kami. Dokumen Anda tetap sepenuhnya aman di perangkat Anda sendiri.',
    'faq.2.q': 'Apakah TacoPDF benar-benar 100% gratis?',
    'faq.2.a': 'Ya, sepenuhnya gratis tanpa biaya tersembunyi, tanpa perlu mendaftar akun, tanpa watermark paksa, dan tanpa batasan jumlah file harian. Kami hanya menampilkan sedikit iklan sponsor (Google AdSense) untuk menutupi biaya server.',
    'faq.3.q': 'Bisakah saya menggunakan alat ini offline tanpa internet?',
    'faq.3.a': 'Bisa! Setelah aplikasi web dimuat di browser Anda untuk pertama kalinya, semua logika pemrosesan PDF berjalan sepenuhnya di sisi klien. Anda dapat memutuskan koneksi internet dengan aman dan melanjutkan proses secara offline penuh.',
    'faq.4.q': 'Mengapa website ini menampilkan iklan?',
    'faq.4.a': 'Sebagai alat utilitas publik yang mengutamakan keamanan tanpa membebankan biaya langganan, iklan sponsor Google AdSense membantu mendanai infrastruktur dasar kami. Kami menempatkan iklan agar tidak mengganggu, nyaman dilihat, dan terpisah dari ruang kerja aktif Anda.',
    'faq.5.q': 'Format file apa saja yang didukung?',
    'faq.5.a': 'TacoPDF mendukung dokumen PDF standar (dari versi 1.0 hingga standar terbaru), serta format file gambar populer seperti PNG, JPG, JPEG, dan WebP untuk diubah menjadi dokumen PDF.',
    'workspace.back': 'Kembali',
    'workspace.tool_config': 'Konfigurasi Alat',
    'workspace.html.title': 'Ketik atau tempel HTML / Teks:',
    'workspace.html.blank': 'Template Dokumen Kosong',
    'workspace.html.invoice': 'Template Faktur Sederhana',
    'workspace.html.letter': 'Surat Memo Resmi',
    'workspace.html.placeholder': 'Masukkan teks...',
    'workspace.drop.title': 'Tarik dan jatuhkan file di sini, atau',
    'workspace.drop.browse': 'jelajahi',
    'workspace.drop.support_img': 'Mendukung gambar PNG, JPG, WebP.',
    'workspace.drop.support_pdf': 'Mendukung file PDF.',
    'workspace.drop.security': 'Eksekusi klien WebAssembly lokal. Keamanan maksimum.',
    'workspace.queue.title': 'Antrean File',
    'workspace.queue.clear': 'Hapus Semua',
    'workspace.btn.compile': 'Kompilasi Dokumen PDF',
    'workspace.btn.run': 'Jalankan',
    'workspace.progress.processing': 'Memproses Wasm lokal...',
    'workspace.progress.error': 'Kesalahan:',
    'workspace.progress.completed': 'Selesai:',
    'workspace.rename.title': 'Ganti Nama File Output:',
    'workspace.rename.placeholder': 'Ganti nama file output',
    'workspace.extract.title': 'Foto Halaman yang Diekstrak',
    'workspace.extract.desc': 'Klik tombol unduh di bawah ini untuk menyimpan setiap halaman langsung sebagai file foto berkualitas tinggi (.png) di perangkat Anda.',
    'workspace.btn.save': 'Simpan',
    'workspace.btn.download': 'Unduh PDF',
    'workspace.btn.preview': 'Pratinjau PDF',
    'workspace.btn.another': '← Proses Dokumen Lain',
    'workspace.custom_name': 'Nama Output Kustom (Opsional)',
    'workspace.custom_name_desc': 'Sesuaikan nama file sebelum diproses. Atau ubah nanti setelah selesai.',
    'workspace.how_to_use': 'Cara Menggunakan & Tips',
    'workspace.how_to_title': 'Cara Menggunakan',
    'workspace.tips_title': 'Tips Profesional & Keamanan',
    'workspace.preview.live': 'Pratinjau PDF sisi klien langsung',
    'workspace.preview.download': 'Unduh',
    'tool.merge.no_settings': '✨ Tidak perlu pengaturan!',
    'tool.merge.desc': 'Cukup jatuhkan file PDF Anda di sebelah kiri. Gunakan tombol panah Atas (↑) dan Bawah (↓) untuk mengurutkannya sesuai urutan yang Anda inginkan, lalu klik tombol tindakan di bawah!',
    'tool.split.keep': 'Halaman mana yang ingin Anda simpan?',
    'tool.split.placeholder': 'misal 1-3, 5 (menyimpan halaman 1, 2, 3 dan 5)',
    'tool.split.guide': '💡 Panduan Mudah:',
    'tool.split.guide1': 'Gunakan tanda hubung (1-3) untuk memilih halaman berurutan.',
    'tool.split.guide2': 'Gunakan koma (1, 4) untuk memisahkan halaman berbeda.',
    'tool.split.guide3': 'Biarkan kolom ini kosong untuk menyimpan semua halaman.',
    'tool.rotate.direction': 'Ke arah mana kami harus memutar halaman Anda?',
    'tool.rotate.90': '90° (Putar Kanan / Samping)',
    'tool.rotate.180': '180° (Putar Terbalik)',
    'tool.rotate.270': '270° (Putar Kiri / Samping)',
    'tool.rotate.apply': 'Terapkan rotasi ke:',
    'tool.rotate.all': 'Setiap halaman',
    'tool.rotate.specific': 'Hanya halaman tertentu',
    'tool.rotate.which': 'Nomor halaman spesifik yang mana?',
    'tool.rotate.placeholder': 'misal 1, 3, 5 (pisahkan dengan koma)',
    'tool.protect.choose': 'Pilih Kata Sandi untuk Mengunci PDF Anda:',
    'tool.protect.placeholder': 'misal rahasia1234 (Buat yang sederhana!)',
    'tool.protect.safe': '🔒 100% Aman & Offline: semuanya terjadi secara pribadi di dalam browser Anda.',
    'tool.protect.important': '⚠️ Penting: Kami tidak dapat memulihkan kata sandi yang terlupa. Harap catat kata sandi Anda!',
    'tool.unlock.type': 'Ketik kata sandi saat ini untuk Membuka Kunci:',
    'tool.unlock.placeholder': 'Ketik kata sandi di sini',
    'tool.unlock.note': '💡 Catatan: Setelah berhasil dibuka kuncinya, Anda dapat membuka dan mencetak PDF Anda dengan mudah tanpa perlu memasukkan kata sandi lagi.',
    'tool.image.size': 'Pilih Ukuran Kertas:',
    'tool.image.a4': 'Ukuran A4 (Kertas printer paling umum)',
    'tool.image.letter': 'Ukuran Letter (Kertas standar)',
    'tool.image.fit': 'Otomatis Pas (Sesuai dimensi gambar)',
    'tool.image.margin': 'Ruang Kosong di sekitar tepi (Margin):',
    'tool.image.margin_note': '💡 Atur ini ke 0 jika Anda ingin gambar Anda mengisi seluruh halaman tanpa batas putih.',
    'tool.pdf2img.title': '📸 Ekstrak Gambar Halaman',
    'tool.pdf2img.desc': 'Tidak perlu pengaturan ekstra! Alat ini akan langsung mengonversi setiap halaman PDF Anda menjadi file gambar (foto) yang mudah dibagikan.',
    'tool.delete.which': 'Nomor halaman mana yang ingin Anda hapus (hilangkan)?',
    'tool.delete.placeholder': 'misal 2, 4 (menghapus halaman 2 dan halaman 4)',
    'tool.delete.example': '💡 Contoh: Ketik 2, 4 untuk menghapus halaman 2 dan 4. Sisa halaman akan otomatis bergeser tanpa menyisakan celah kosong!',
    'tool.extract.which': 'Halaman mana yang ingin Anda simpan sebagai file baru?',
    'tool.extract.placeholder': 'misal 1, 3, 5 (hanya menyimpan halaman 1, 3, 5)',
    'tool.extract.how': '💡 Cara kerjanya: Ketik halaman yang ingin Anda simpan. Ini menciptakan PDF baru dan ringan yang hanya berisi halaman-halaman tersebut.',
    'tool.watermark.type': 'Ketik Teks Watermark Anda:',
    'tool.watermark.placeholder': 'misal DRAFT, SALINAN, RAHASIA',
    'tool.watermark.size': 'Ukuran Teks:',
    'tool.watermark.opacity': 'Tingkat Tembus Pandang (Opacity):',
    'tool.watermark.color': 'Pilih Warna Teks:',
    'tool.watermark.rotation': 'Sudut Kemiringan (Rotasi):',
    'tool.watermark.note': '💡 Opacity 0.2 sangat ringan dan pudar. 1.0 adalah solid.',
    'tool.page_num.how': 'Bagaimana tampilan nomor halamannya?',
    'tool.page_num.placeholder': 'misal Halaman {n} dari {total}',
    'tool.page_num.hint': '💡 Petunjuk: {n} berubah menjadi nomor halaman (1, 2, 3), dan {total} menunjukkan total halaman (misal, Halaman 1 dari 5).',
    'tool.page_num.placement': 'Penempatan Posisi:',
    'tool.page_num.bottom_center': 'Bawah Tengah (Paling Populer)',
    'tool.page_num.bottom_right': 'Sudut Kanan Bawah',
    'tool.page_num.bottom_left': 'Sudut Kiri Bawah',
    'tool.page_num.top_center': 'Atas Tengah',
    'tool.page_num.top_right': 'Sudut Kanan Atas'
  },
  es: {
    'faq.1.q': '¿Es seguro procesar archivos PDF aquí?',
    'faq.1.a': 'Absolutamente. Todos los archivos se procesan localmente en la memoria de su navegador utilizando módulos WebAssembly de alto rendimiento. Ni un solo byte de sus documentos es subido o enviado a nuestros servidores.',
    'faq.2.q': '¿Es TacoPDF verdaderamente 100% gratuito?',
    'faq.2.a': 'Sí, totalmente gratuito, sin cargos ocultos, sin registro obligatorio, sin marcas de agua forzadas. Mostramos publicidad no intrusiva de patrocinadores (Google AdSense) para cubrir los costos del servidor.',
    'faq.3.q': '¿Puedo usar esta herramienta sin internet?',
    'faq.3.a': '¡Sí! Una vez que la aplicación web se carga en su navegador por primera vez, toda la lógica de procesamiento funciona completamente en el lado del cliente. Puede desconectar su internet y continuar usándolo.',
    'faq.4.q': '¿Por qué este sitio web muestra anuncios?',
    'faq.4.a': 'Como herramienta pública gratuita, los anuncios de Google AdSense ayudan a financiar nuestra infraestructura básica. Optimizamos la ubicación de los anuncios para que no sean molestos.',
    'faq.5.q': '¿Qué formatos de archivo son compatibles?',
    'faq.5.a': 'TacoPDF admite cualquier documento PDF estándar, así como formatos de archivo de imagen populares como PNG, JPG, JPEG y WebP para convertirlos en documentos PDF de calidad.',
    'workspace.back': 'Atrás',
    'workspace.tool_config': 'Configuraciones',
    'workspace.html.title': 'Escriba o pegue HTML / Texto:',
    'workspace.html.blank': 'Plantilla en blanco',
    'workspace.html.invoice': 'Plantilla de factura simple',
    'workspace.html.letter': 'Carta oficial',
    'workspace.html.placeholder': 'Ingrese texto...',
    'workspace.drop.title': 'Arrastre y suelte archivos aquí, o',
    'workspace.drop.browse': 'explorar',
    'workspace.drop.support_img': 'Soporta imágenes PNG, JPG, WebP.',
    'workspace.drop.support_pdf': 'Soporta archivos PDF.',
    'workspace.drop.security': 'Ejecución local del lado del cliente. Máxima seguridad.',
    'workspace.queue.title': 'Archivos en Cola',
    'workspace.queue.clear': 'Borrar Todo',
    'workspace.btn.compile': 'Compilar Documento PDF',
    'workspace.btn.run': 'Ejecutar',
    'workspace.progress.processing': 'Procesando localmente...',
    'workspace.progress.error': 'Error:',
    'workspace.progress.completed': 'Completado:',
    'workspace.rename.title': 'Renombrar Archivo de Salida:',
    'workspace.rename.placeholder': 'Renombrar archivo de salida',
    'workspace.extract.title': 'Fotos de Páginas Extraídas',
    'workspace.extract.desc': 'Haga clic en los botones de descarga a continuación para guardar cada página como una foto de alta calidad (.png).',
    'workspace.btn.save': 'Guardar',
    'workspace.btn.download': 'Descargar PDF',
    'workspace.btn.preview': 'Vista Previa de PDF',
    'workspace.btn.another': '← Procesar Otro Documento',
    'workspace.custom_name': 'Nombre de Salida Personalizado (Opcional)',
    'workspace.custom_name_desc': 'Personalice el nombre del archivo antes de procesarlo. O cámbielo más tarde.',
    'workspace.how_to_use': 'Cómo Usar y Consejos',
    'workspace.how_to_title': 'Cómo Usar',
    'workspace.tips_title': 'Consejos Profesionales y de Seguridad',
    'workspace.preview.live': 'Vista previa en vivo del lado del cliente',
    'workspace.preview.download': 'Descargar',
    'tool.merge.no_settings': '✨ ¡No se necesitan configuraciones!',
    'tool.merge.desc': 'Simplemente suelte sus archivos PDF a la izquierda. Use los botones de flecha Arriba y Abajo para organizarlos y luego haga clic en el botón de acción.',
    'tool.split.keep': '¿Qué páginas desea conservar?',
    'tool.split.placeholder': 'ej. 1-3, 5 (conserva las páginas 1, 2, 3 y 5)',
    'tool.split.guide': '💡 Guía Fácil:',
    'tool.split.guide1': 'Use un guion (1-3) para seleccionar páginas consecutivas.',
    'tool.split.guide2': 'Use una coma (1, 4) para separar páginas diferentes.',
    'tool.split.guide3': 'Deje este campo vacío para conservar todas las páginas.',
    'tool.rotate.direction': '¿En qué dirección debemos girar sus páginas?',
    'tool.rotate.90': '90° (Girar a la Derecha)',
    'tool.rotate.180': '180° (Al Revés)',
    'tool.rotate.270': '270° (Girar a la Izquierda)',
    'tool.rotate.apply': 'Aplicar rotación a:',
    'tool.rotate.all': 'Cada página',
    'tool.rotate.specific': 'Solo páginas específicas',
    'tool.rotate.which': '¿Qué números de página específicos?',
    'tool.rotate.placeholder': 'ej. 1, 3, 5 (separados por comas)',
    'tool.protect.choose': 'Elija una Contraseña para Bloquear su PDF:',
    'tool.protect.placeholder': 'ej. secreto1234 (¡Manténgalo simple!)',
    'tool.protect.safe': '🔒 100% Seguro y Fuera de Línea: todo sucede de forma privada en su navegador.',
    'tool.protect.important': '⚠️ Importante: No podemos recuperar contraseñas olvidadas. ¡Por favor anote su contraseña!',
    'tool.unlock.type': 'Escriba la contraseña actual para Desbloquear:',
    'tool.unlock.placeholder': 'Escriba la contraseña aquí',
    'tool.unlock.note': '💡 Nota: Una vez desbloqueado con éxito, puede abrir y ver su PDF fácilmente sin ingresar una contraseña.',
    'tool.image.size': 'Seleccionar Tamaño de Papel:',
    'tool.image.a4': 'Tamaño A4',
    'tool.image.letter': 'Tamaño Carta',
    'tool.image.fit': 'Ajuste Automático',
    'tool.image.margin': 'Espacio en Blanco alrededor de los bordes (Márgenes):',
    'tool.image.margin_note': '💡 Establezca esto en 0 si desea que sus imágenes llenen toda la página sin bordes blancos.',
    'tool.pdf2img.title': '📸 Extraer Imágenes de Páginas',
    'tool.pdf2img.desc': '¡No se necesitan ajustes adicionales! Esta herramienta convertirá instantáneamente cada página en una imagen.',
    'tool.delete.which': '¿Qué números de página desea eliminar?',
    'tool.delete.placeholder': 'ej. 2, 4 (elimina la página 2 y 4)',
    'tool.delete.example': '💡 Ejemplo: Escriba 2, 4 para eliminar las páginas 2 y 4. ¡Las páginas restantes se deslizarán automáticamente en su lugar!',
    'tool.extract.which': '¿Qué páginas desea conservar como un archivo nuevo?',
    'tool.extract.placeholder': 'ej. 1, 3, 5 (solo conserva 1, 3, 5)',
    'tool.extract.how': '💡 Cómo funciona: Escriba las páginas que desea conservar. Esto crea un nuevo PDF que contiene solo estas páginas.',
    'tool.watermark.type': 'Escriba su Texto de Marca de Agua:',
    'tool.watermark.placeholder': 'ej. BORRADOR, COPIA, CONFIDENCIAL',
    'tool.watermark.size': 'Tamaño del Texto:',
    'tool.watermark.opacity': 'Nivel de Transparencia (Opacidad):',
    'tool.watermark.color': 'Elegir Color del Texto:',
    'tool.watermark.rotation': 'Ángulo de Inclinación (Rotación):',
    'tool.watermark.note': '💡 Una opacidad de 0.2 es muy clara y difuminada. 1.0 es sólida.',
    'tool.page_num.how': '¿Cómo deberían verse los números de página?',
    'tool.page_num.placeholder': 'ej. Página {n} de {total}',
    'tool.page_num.hint': '💡 Sugerencia: {n} cambia al número de página, y {total} muestra el total de páginas.',
    'tool.page_num.placement': 'Alineación de Ubicación:',
    'tool.page_num.bottom_center': 'Abajo al Centro (Más Popular)',
    'tool.page_num.bottom_right': 'Esquina Inferior Derecha',
    'tool.page_num.bottom_left': 'Esquina Inferior Izquierda',
    'tool.page_num.top_center': 'Arriba al Centro',
    'tool.page_num.top_right': 'Esquina Superior Derecha'
  },
  ja: {
    'faq.1.q': 'ここでPDFファイルを処理するのは安全ですか？',
    'faq.1.a': 'はい、完全に安全です。すべてのファイルはブラウザのメモリ内でローカルに処理されます。ドキュメントがサーバーにアップロードされることはありません。',
    'faq.2.q': 'TacoPDFは本当に100%無料ですか？',
    'faq.2.a': 'はい、隠し料金、アカウント登録、透かし、ファイル数制限なしで完全に無料です。インフラ費用をカバーするために、少数のスポンサー広告を表示しています。',
    'faq.3.q': 'インターネットなしのオフラインでも使えますか？',
    'faq.3.a': 'はい！ウェブアプリが一度ブラウザに読み込まれれば、処理は完全にクライアント側で実行されるため、オフラインでも安全に使用できます。',
    'faq.4.q': 'なぜ広告が表示されるのですか？',
    'faq.4.a': 'サブスクリプション料金を請求せずにセキュリティを重視する公開ツールとして、Google AdSense広告がインフラの資金源となっています。',
    'faq.5.q': 'どのファイル形式に対応していますか？',
    'faq.5.a': 'すべての標準PDFドキュメントのほか、PNG、JPG、JPEG、WebPなどの人気のある画像形式に対応しています。',
    'workspace.back': '戻る',
    'workspace.tool_config': 'ツール設定',
    'workspace.html.title': 'HTML / リッチテキストを入力:',
    'workspace.html.blank': '空白テンプレート',
    'workspace.html.invoice': '簡単な請求書テンプレート',
    'workspace.html.letter': '公式メモレター',
    'workspace.html.placeholder': 'テキストを入力...',
    'workspace.drop.title': 'ここにファイルをドロップ、または',
    'workspace.drop.browse': '参照',
    'workspace.drop.support_img': 'PNG、JPG、WebP画像に対応。',
    'workspace.drop.support_pdf': 'PDFファイルに対応。',
    'workspace.drop.security': 'ローカルクライアント側で実行。最高セキュリティ。',
    'workspace.queue.title': '待機中のファイル',
    'workspace.queue.clear': 'すべてクリア',
    'workspace.btn.compile': 'PDFドキュメントをコンパイル',
    'workspace.btn.run': '実行',
    'workspace.progress.processing': 'ローカルで処理中...',
    'workspace.progress.error': 'エラー:',
    'workspace.progress.completed': '完了:',
    'workspace.rename.title': '出力ファイル名を変更:',
    'workspace.rename.placeholder': 'ファイル名を変更',
    'workspace.extract.title': '抽出されたページの画像',
    'workspace.extract.desc': '下のダウンロードボタンをクリックして、各ページを高品質な画像（.png）として保存します。',
    'workspace.btn.save': '保存',
    'workspace.btn.download': 'PDFをダウンロード',
    'workspace.btn.preview': 'PDFプレビュー',
    'workspace.btn.another': '← 別のドキュメントを処理',
    'workspace.custom_name': 'カスタム出力名（オプション）',
    'workspace.custom_name_desc': '処理前にファイル名をカスタマイズするか、後で変更できます。',
    'workspace.how_to_use': '使い方とヒント',
    'workspace.how_to_title': '使い方',
    'workspace.tips_title': 'プロとセキュリティのヒント',
    'workspace.preview.live': 'ライブ クライアント側プレビュー',
    'workspace.preview.download': 'ダウンロード',
    'tool.merge.no_settings': '✨ 設定は不要です！',
    'tool.merge.desc': '左側にPDFファイルをドロップし、矢印ボタンを使って順序を並べ替えてください。',
    'tool.split.keep': 'どのページを保持しますか？',
    'tool.split.placeholder': '例: 1-3, 5',
    'tool.split.guide': '💡 ガイド:',
    'tool.split.guide1': 'ハイフン (1-3) で連続したページを選択。',
    'tool.split.guide2': 'カンマ (1, 4) で別々のページを区切ります。',
    'tool.split.guide3': 'すべてのページを保持するには、ここを空白のままにします。',
    'tool.rotate.direction': 'ページをどの方向に回転させますか？',
    'tool.rotate.90': '90° (右回転)',
    'tool.rotate.180': '180° (上下逆)',
    'tool.rotate.270': '270° (左回転)',
    'tool.rotate.apply': '回転を適用:',
    'tool.rotate.all': 'すべてのページ',
    'tool.rotate.specific': '特定のページのみ',
    'tool.rotate.which': 'どのページ番号ですか？',
    'tool.rotate.placeholder': '例: 1, 3, 5',
    'tool.protect.choose': 'PDFをロックするパスワードを選択:',
    'tool.protect.placeholder': '例: secret1234',
    'tool.protect.safe': '🔒 100% 安全でオフライン: すべてブラウザ内でプライベートに行われます。',
    'tool.protect.important': '⚠️ 重要: パスワードを忘れた場合、復元することはできません！',
    'tool.unlock.type': 'ロック解除するための現在のパスワードを入力:',
    'tool.unlock.placeholder': 'ここにパスワードを入力',
    'tool.unlock.note': '💡 メモ: ロック解除に成功すると、パスワードなしでPDFを簡単に開くことができます。',
    'tool.image.size': '用紙サイズを選択:',
    'tool.image.a4': 'A4サイズ',
    'tool.image.letter': 'レターサイズ',
    'tool.image.fit': '自動調整',
    'tool.image.margin': '余白:',
    'tool.image.margin_note': '💡 画像をページ全体に配置するには、これを0に設定します。',
    'tool.pdf2img.title': '📸 ページ画像を抽出',
    'tool.pdf2img.desc': '追加の設定は不要です！各ページを瞬時に画像ファイルに変換します。',
    'tool.delete.which': '削除したいページ番号はどれですか？',
    'tool.delete.placeholder': '例: 2, 4',
    'tool.delete.example': '💡 例: 2, 4 と入力するとページ2と4が削除されます。残りのページは自動的に詰められます。',
    'tool.extract.which': 'どのページを新しいファイルとして保持しますか？',
    'tool.extract.placeholder': '例: 1, 3, 5',
    'tool.extract.how': '💡 使い方: 保持したいページを入力します。',
    'tool.watermark.type': '透かしのテキストを入力:',
    'tool.watermark.placeholder': '例: DRAFT, COPY, 極秘',
    'tool.watermark.size': 'テキストのサイズ:',
    'tool.watermark.opacity': '不透明度:',
    'tool.watermark.color': 'テキストの色を選択:',
    'tool.watermark.rotation': '回転角度:',
    'tool.watermark.note': '💡 不透明度0.2は非常に薄く、1.0はベタ塗りです。',
    'tool.page_num.how': 'ページ番号をどのように表示しますか？',
    'tool.page_num.placeholder': '例: Page {n} of {total}',
    'tool.page_num.hint': '💡 ヒント: {n} はページ番号、{total} は合計ページ数を示します。',
    'tool.page_num.placement': '配置位置:',
    'tool.page_num.bottom_center': '中央下',
    'tool.page_num.bottom_right': '右下',
    'tool.page_num.bottom_left': '左下',
    'tool.page_num.top_center': '中央上',
    'tool.page_num.top_right': '右上'
  },
  pt: {
    'faq.1.q': 'É seguro processar arquivos PDF aqui?',
    'faq.1.a': 'Absolutamente. Todos os arquivos são processados localmente na memória do seu navegador. Nenhum byte de seus documentos é enviado para nossos servidores.',
    'faq.2.q': 'O TacoPDF é realmente 100% gratuito?',
    'faq.2.a': 'Sim, totalmente gratuito, sem taxas ocultas, sem necessidade de registro. Exibimos alguns anúncios não intrusivos para ajudar a cobrir os custos do servidor.',
    'faq.3.q': 'Posso usar esta ferramenta offline sem internet?',
    'faq.3.a': 'Sim! Uma vez carregado no seu navegador, todo o processamento funciona no lado do cliente. Você pode se desconectar da internet e continuar usando offline.',
    'faq.4.q': 'Por que este site exibe anúncios?',
    'faq.4.a': 'Como uma ferramenta gratuita focada na segurança, os anúncios do Google AdSense ajudam a financiar nossa infraestrutura.',
    'faq.5.q': 'Quais formatos de arquivo são suportados?',
    'faq.5.a': 'O TacoPDF suporta qualquer documento PDF padrão, bem como formatos de imagem como PNG, JPG, JPEG e WebP para conversão.',
    'workspace.back': 'Voltar',
    'workspace.tool_config': 'Configurações',
    'workspace.html.title': 'Digite ou cole HTML / Texto:',
    'workspace.html.blank': 'Modelo em branco',
    'workspace.html.invoice': 'Modelo de Fatura',
    'workspace.html.letter': 'Carta Oficial',
    'workspace.html.placeholder': 'Insira o texto...',
    'workspace.drop.title': 'Arraste e solte arquivos aqui, ou',
    'workspace.drop.browse': 'procurar',
    'workspace.drop.support_img': 'Suporta imagens PNG, JPG, WebP.',
    'workspace.drop.support_pdf': 'Suporta arquivos PDF.',
    'workspace.drop.security': 'Execução local no cliente. Segurança máxima.',
    'workspace.queue.title': 'Arquivos na Fila',
    'workspace.queue.clear': 'Limpar Tudo',
    'workspace.btn.compile': 'Compilar Documento PDF',
    'workspace.btn.run': 'Executar',
    'workspace.progress.processing': 'Processando localmente...',
    'workspace.progress.error': 'Erro:',
    'workspace.progress.completed': 'Concluído:',
    'workspace.rename.title': 'Renomear Arquivo de Saída:',
    'workspace.rename.placeholder': 'Renomear arquivo de saída',
    'workspace.extract.title': 'Fotos de Páginas Extraídas',
    'workspace.extract.desc': 'Clique nos botões de download abaixo para salvar cada página como uma foto de alta qualidade (.png).',
    'workspace.btn.save': 'Salvar',
    'workspace.btn.download': 'Baixar PDF',
    'workspace.btn.preview': 'Visualizar PDF',
    'workspace.btn.another': '← Processar Outro Documento',
    'workspace.custom_name': 'Nome de Saída Personalizado (Opcional)',
    'workspace.custom_name_desc': 'Personalize o nome do arquivo antes ou depois do processamento.',
    'workspace.how_to_use': 'Como Usar e Dicas',
    'workspace.how_to_title': 'Como Usar',
    'workspace.tips_title': 'Dicas de Segurança e Profissionais',
    'workspace.preview.live': 'Visualização ao vivo do lado do cliente',
    'workspace.preview.download': 'Baixar',
    'tool.merge.no_settings': '✨ Não é necessário configuração!',
    'tool.merge.desc': 'Basta soltar seus PDFs à esquerda. Use os botões de seta para cima e para baixo para organizá-los e clique no botão de ação!',
    'tool.split.keep': 'Quais páginas você deseja manter?',
    'tool.split.placeholder': 'ex. 1-3, 5',
    'tool.split.guide': '💡 Guia Fácil:',
    'tool.split.guide1': 'Use um traço (1-3) para selecionar páginas consecutivas.',
    'tool.split.guide2': 'Use uma vírgula (1, 4) para separar páginas.',
    'tool.split.guide3': 'Deixe em branco para manter todas as páginas.',
    'tool.rotate.direction': 'Em qual direção devemos girar suas páginas?',
    'tool.rotate.90': '90° (Direita)',
    'tool.rotate.180': '180° (De Cabeça para Baixo)',
    'tool.rotate.270': '270° (Esquerda)',
    'tool.rotate.apply': 'Aplicar rotação em:',
    'tool.rotate.all': 'Todas as páginas',
    'tool.rotate.specific': 'Apenas páginas específicas',
    'tool.rotate.which': 'Quais números de página?',
    'tool.rotate.placeholder': 'ex. 1, 3, 5 (separados por vírgula)',
    'tool.protect.choose': 'Escolha uma Senha para Bloquear seu PDF:',
    'tool.protect.placeholder': 'ex. secreto1234',
    'tool.protect.safe': '🔒 100% Seguro e Offline: tudo acontece no seu navegador.',
    'tool.protect.important': '⚠️ Importante: Não podemos recuperar senhas. Por favor, anote sua senha!',
    'tool.unlock.type': 'Digite a senha atual para Desbloquear:',
    'tool.unlock.placeholder': 'Digite a senha aqui',
    'tool.unlock.note': '💡 Nota: Uma vez desbloqueado, você pode abrir e visualizar seu PDF sem senha.',
    'tool.image.size': 'Selecione o Tamanho do Papel:',
    'tool.image.a4': 'Tamanho A4',
    'tool.image.letter': 'Tamanho Carta',
    'tool.image.fit': 'Ajuste Automático',
    'tool.image.margin': 'Espaço em Branco nas bordas (Margens):',
    'tool.image.margin_note': '💡 Defina como 0 se quiser que suas imagens preencham toda a página sem bordas.',
    'tool.pdf2img.title': '📸 Extrair Imagens das Páginas',
    'tool.pdf2img.desc': 'Sem configurações extras! Esta ferramenta converterá instantaneamente cada página em imagem.',
    'tool.delete.which': 'Quais números de página você deseja excluir?',
    'tool.delete.placeholder': 'ex. 2, 4',
    'tool.delete.example': '💡 Exemplo: Digite 2, 4 para remover as páginas 2 e 4.',
    'tool.extract.which': 'Quais páginas você deseja manter como um novo arquivo?',
    'tool.extract.placeholder': 'ex. 1, 3, 5',
    'tool.extract.how': '💡 Como funciona: Digite as páginas que deseja manter. Isso cria um novo PDF com essas páginas.',
    'tool.watermark.type': 'Digite o Texto da Marca de água:',
    'tool.watermark.placeholder': 'ex. RASCUNHO, CÓPIA',
    'tool.watermark.size': 'Tamanho do Texto:',
    'tool.watermark.opacity': 'Nível de Transparência (Opacidade):',
    'tool.watermark.color': 'Escolher Cor do Texto:',
    'tool.watermark.rotation': 'Ângulo de Rotação:',
    'tool.watermark.note': '💡 Uma opacidade de 0.2 é muito clara e esmaecida. 1.0 é sólida.',
    'tool.page_num.how': 'Como os números de página devem parecer?',
    'tool.page_num.placeholder': 'ex. Página {n} de {total}',
    'tool.page_num.hint': '💡 Dica: {n} muda para o número da página, e {total} mostra o total de páginas.',
    'tool.page_num.placement': 'Alinhamento:',
    'tool.page_num.bottom_center': 'Inferior Centro',
    'tool.page_num.bottom_right': 'Inferior Direito',
    'tool.page_num.bottom_left': 'Inferior Esquerdo',
    'tool.page_num.top_center': 'Superior Centro',
    'tool.page_num.top_right': 'Superior Direito'
  },
  de: {
    'faq.1.q': 'Ist die Bearbeitung von PDF-Dateien hier sicher?',
    'faq.1.a': 'Absolut. Alle Dateien werden lokal im Browser verarbeitet. Kein einziges Byte Ihrer Dokumente wird auf unsere Server hochgeladen.',
    'faq.2.q': 'Ist TacoPDF wirklich 100% kostenlos?',
    'faq.2.a': 'Ja, völlig kostenlos, keine versteckten Gebühren, keine Anmeldung erforderlich. Wir zeigen unaufdringliche Werbung an, um die Serverkosten zu decken.',
    'faq.3.q': 'Kann ich dieses Tool offline verwenden?',
    'faq.3.a': 'Ja! Sobald die Web-App geladen ist, läuft die Verarbeitung vollständig clientseitig. Sie können offline weiterarbeiten.',
    'faq.4.q': 'Warum zeigt diese Website Werbung?',
    'faq.4.a': 'Als kostenloses Tool finanzieren Google AdSense-Anzeigen unsere Infrastruktur.',
    'faq.5.q': 'Welche Dateiformate werden unterstützt?',
    'faq.5.a': 'Wir unterstützen alle Standard-PDFs sowie beliebte Bildformate wie PNG, JPG, JPEG und WebP.',
    'workspace.back': 'Zurück',
    'workspace.tool_config': 'Konfigurationen',
    'workspace.html.title': 'HTML / Text eingeben oder einfügen:',
    'workspace.html.blank': 'Leere Vorlage',
    'workspace.html.invoice': 'Rechnungsvorlage',
    'workspace.html.letter': 'Offizieller Brief',
    'workspace.html.placeholder': 'Text eingeben...',
    'workspace.drop.title': 'Dateien hierhin ziehen, oder',
    'workspace.drop.browse': 'durchsuchen',
    'workspace.drop.support_img': 'Unterstützt PNG-, JPG- und WebP-Bilder.',
    'workspace.drop.support_pdf': 'Unterstützt PDF-Dateien.',
    'workspace.drop.security': 'Lokale clientseitige Verarbeitung. Höchste Sicherheit.',
    'workspace.queue.title': 'Dateien in Warteschlange',
    'workspace.queue.clear': 'Alle löschen',
    'workspace.btn.compile': 'PDF-Dokument erstellen',
    'workspace.btn.run': 'Ausführen',
    'workspace.progress.processing': 'Lokal verarbeiten...',
    'workspace.progress.error': 'Fehler:',
    'workspace.progress.completed': 'Abgeschlossen:',
    'workspace.rename.title': 'Ausgabedatei umbenennen:',
    'workspace.rename.placeholder': 'Ausgabedatei umbenennen',
    'workspace.extract.title': 'Extrahierte Seitenfotos',
    'workspace.extract.desc': 'Klicken Sie auf die Download-Buttons unten, um jede Seite als hochwertiges Foto (.png) zu speichern.',
    'workspace.btn.save': 'Speichern',
    'workspace.btn.download': 'PDF Herunterladen',
    'workspace.btn.preview': 'PDF Vorschau',
    'workspace.btn.another': '← Ein weiteres Dokument bearbeiten',
    'workspace.custom_name': 'Benutzerdefinierter Name (optional)',
    'workspace.custom_name_desc': 'Passen Sie den Dateinamen vor oder nach der Verarbeitung an.',
    'workspace.how_to_use': 'Benutzung und Tipps',
    'workspace.how_to_title': 'Benutzung',
    'workspace.tips_title': 'Profitipps und Sicherheit',
    'workspace.preview.live': 'Live-Vorschau (clientseitig)',
    'workspace.preview.download': 'Herunterladen',
    'tool.merge.no_settings': '✨ Keine Einstellungen nötig!',
    'tool.merge.desc': 'Legen Sie Ihre PDF-Dateien links ab. Nutzen Sie die Pfeile (Auf/Ab) zur Sortierung und klicken Sie dann auf den Button unten!',
    'tool.split.keep': 'Welche Seiten möchten Sie behalten?',
    'tool.split.placeholder': 'z.B. 1-3, 5 (behält die Seiten 1, 2, 3 und 5)',
    'tool.split.guide': '💡 Kurzanleitung:',
    'tool.split.guide1': 'Einen Bindestrich (1-3) für aufeinanderfolgende Seiten nutzen.',
    'tool.split.guide2': 'Ein Komma (1, 4) zur Trennung nutzen.',
    'tool.split.guide3': 'Dieses Feld leer lassen, um alle Seiten zu behalten.',
    'tool.rotate.direction': 'In welche Richtung sollen die Seiten gedreht werden?',
    'tool.rotate.90': '90° (Nach rechts drehen)',
    'tool.rotate.180': '180° (Auf den Kopf stellen)',
    'tool.rotate.270': '270° (Nach links drehen)',
    'tool.rotate.apply': 'Rotation anwenden auf:',
    'tool.rotate.all': 'Jede Seite',
    'tool.rotate.specific': 'Nur bestimmte Seiten',
    'tool.rotate.which': 'Welche bestimmten Seitenzahlen?',
    'tool.rotate.placeholder': 'z.B. 1, 3, 5',
    'tool.protect.choose': 'Wählen Sie ein Passwort zum Sperren Ihres PDFs:',
    'tool.protect.placeholder': 'z.B. geheim1234',
    'tool.protect.safe': '🔒 100% Sicher & Offline: alles geschieht privat in Ihrem Browser.',
    'tool.protect.important': '⚠️ Wichtig: Wir können vergessene Passwörter nicht wiederherstellen!',
    'tool.unlock.type': 'Geben Sie das aktuelle Passwort zum Entsperren ein:',
    'tool.unlock.placeholder': 'Passwort hier eingeben',
    'tool.unlock.note': '💡 Hinweis: Nach dem Entsperren können Sie Ihr PDF dauerhaft ohne Passwort öffnen.',
    'tool.image.size': 'Papierformat auswählen:',
    'tool.image.a4': 'A4-Format',
    'tool.image.letter': 'Letter-Format',
    'tool.image.fit': 'Automatisch anpassen',
    'tool.image.margin': 'Leerraum um die Ränder (Ränder):',
    'tool.image.margin_note': '💡 Auf 0 setzen, wenn Bilder die gesamte Seite füllen sollen.',
    'tool.pdf2img.title': '📸 Seitenbilder extrahieren',
    'tool.pdf2img.desc': 'Keine zusätzlichen Einstellungen erforderlich!',
    'tool.delete.which': 'Welche Seiten möchten Sie löschen?',
    'tool.delete.placeholder': 'z.B. 2, 4',
    'tool.delete.example': '💡 Beispiel: Geben Sie 2, 4 ein, um die Seiten 2 und 4 zu entfernen.',
    'tool.extract.which': 'Welche Seiten möchten Sie als neue Datei behalten?',
    'tool.extract.placeholder': 'z.B. 1, 3, 5',
    'tool.extract.how': '💡 Wie es funktioniert: Geben Sie die gewünschten Seiten ein. Dies erstellt ein neues PDF mit diesen Seiten.',
    'tool.watermark.type': 'Geben Sie Ihren Wasserzeichen-Text ein:',
    'tool.watermark.placeholder': 'z.B. ENTWURF, KOPIE',
    'tool.watermark.size': 'Textgröße:',
    'tool.watermark.opacity': 'Transparenzgrad (Deckkraft):',
    'tool.watermark.color': 'Textfarbe wählen:',
    'tool.watermark.rotation': 'Neigungswinkel (Rotation):',
    'tool.watermark.note': '💡 Eine Deckkraft von 0.2 ist sehr hell, 1.0 ist deckend.',
    'tool.page_num.how': 'Wie sollen die Seitenzahlen aussehen?',
    'tool.page_num.placeholder': 'z.B. Seite {n} von {total}',
    'tool.page_num.hint': '💡 Hinweis: {n} wird zur Seitenzahl, {total} zeigt die Gesamtzahl an.',
    'tool.page_num.placement': 'Platzierung:',
    'tool.page_num.bottom_center': 'Unten Mitte',
    'tool.page_num.bottom_right': 'Unten Rechts',
    'tool.page_num.bottom_left': 'Unten Links',
    'tool.page_num.top_center': 'Oben Mitte',
    'tool.page_num.top_right': 'Oben Rechts'
  },
  fr: {
    'faq.1.q': 'Est-il sûr de traiter des fichiers PDF ici ?',
    'faq.1.a': 'Absolument. Tous les fichiers sont traités localement dans la mémoire de votre navigateur. Pas un seul octet n est envoyé sur nos serveurs.',
    'faq.2.q': 'TacoPDF est-il vraiment 100% gratuit ?',
    'faq.2.a': 'Oui, totalement gratuit, sans frais cachés, sans inscription. Nous affichons des publicités non intrusives pour couvrir les frais de serveur.',
    'faq.3.q': 'Puis-je utiliser cet outil hors ligne sans Internet ?',
    'faq.3.a': 'Oui ! Une fois l application Web chargée, tout le traitement s effectue côté client. Vous pouvez vous déconnecter et continuer à travailler.',
    'faq.4.q': 'Pourquoi ce site affiche-t-il des publicités ?',
    'faq.4.a': 'En tant qu outil gratuit, les annonces Google AdSense aident à financer notre infrastructure.',
    'faq.5.q': 'Quels formats de fichiers sont pris en charge ?',
    'faq.5.a': 'Nous prenons en charge tous les documents PDF standard, ainsi que les formats d image populaires tels que PNG, JPG, JPEG et WebP.',
    'workspace.back': 'Retour',
    'workspace.tool_config': 'Configurations',
    'workspace.html.title': 'Tapez ou collez le code HTML / Texte enrichi :',
    'workspace.html.blank': 'Modèle vierge',
    'workspace.html.invoice': 'Modèle de facture simple',
    'workspace.html.letter': 'Lettre officielle',
    'workspace.html.placeholder': 'Entrez le texte...',
    'workspace.drop.title': 'Glissez-déposez les fichiers ici, ou',
    'workspace.drop.browse': 'parcourir',
    'workspace.drop.support_img': 'Prend en charge les images PNG, JPG, WebP.',
    'workspace.drop.support_pdf': 'Prend en charge les fichiers PDF.',
    'workspace.drop.security': 'Exécution locale côté client. Sécurité maximale.',
    'workspace.queue.title': 'Fichiers en File d attente',
    'workspace.queue.clear': 'Tout effacer',
    'workspace.btn.compile': 'Compiler le Document PDF',
    'workspace.btn.run': 'Exécuter',
    'workspace.progress.processing': 'Traitement local en cours...',
    'workspace.progress.error': 'Erreur :',
    'workspace.progress.completed': 'Terminé :',
    'workspace.rename.title': 'Renommer le fichier de sortie :',
    'workspace.rename.placeholder': 'Renommer le fichier',
    'workspace.extract.title': 'Photos de pages extraites',
    'workspace.extract.desc': 'Cliquez sur les boutons de téléchargement ci-dessous pour enregistrer chaque page sous forme de photo de haute qualité (.png).',
    'workspace.btn.save': 'Enregistrer',
    'workspace.btn.download': 'Télécharger le PDF',
    'workspace.btn.preview': 'Aperçu du PDF',
    'workspace.btn.another': '← Traiter Un Autre Document',
    'workspace.custom_name': 'Nom de Sortie Personnalisé (Optionnel)',
    'workspace.custom_name_desc': 'Personnalisez le nom du fichier avant ou après le traitement.',
    'workspace.how_to_use': 'Comment utiliser et conseils',
    'workspace.how_to_title': 'Comment utiliser',
    'workspace.tips_title': 'Conseils de sécurité',
    'workspace.preview.live': 'Aperçu en direct côté client',
    'workspace.preview.download': 'Télécharger',
    'tool.merge.no_settings': '✨ Aucun paramètre nécessaire !',
    'tool.merge.desc': 'Déposez simplement vos fichiers PDF sur la gauche. Utilisez les boutons fléchés pour les organiser, puis cliquez sur le bouton d action ci-dessous !',
    'tool.split.keep': 'Quelles pages souhaitez-vous conserver ?',
    'tool.split.placeholder': 'ex. 1-3, 5',
    'tool.split.guide': '💡 Guide Facile :',
    'tool.split.guide1': 'Utilisez un tiret (1-3) pour sélectionner des pages consécutives.',
    'tool.split.guide2': 'Utilisez une virgule (1, 4) pour séparer différentes pages.',
    'tool.split.guide3': 'Laissez ce champ vide pour conserver toutes les pages.',
    'tool.rotate.direction': 'Dans quelle direction devons-nous tourner vos pages ?',
    'tool.rotate.90': '90° (Tourner à droite)',
    'tool.rotate.180': '180° (À l envers)',
    'tool.rotate.270': '270° (Tourner à gauche)',
    'tool.rotate.apply': 'Appliquer la rotation à :',
    'tool.rotate.all': 'Chaque page',
    'tool.rotate.specific': 'Pages spécifiques uniquement',
    'tool.rotate.which': 'Quels numéros de page ?',
    'tool.rotate.placeholder': 'ex. 1, 3, 5',
    'tool.protect.choose': 'Choisissez un mot de passe pour verrouiller votre PDF :',
    'tool.protect.placeholder': 'ex. secret1234',
    'tool.protect.safe': '🔒 100% Sûr et Hors ligne : tout se passe dans votre navigateur.',
    'tool.protect.important': '⚠️ Important : Nous ne pouvons pas récupérer les mots de passe. Veuillez le noter !',
    'tool.unlock.type': 'Tapez le mot de passe actuel pour Déverrouiller :',
    'tool.unlock.placeholder': 'Tapez le mot de passe ici',
    'tool.unlock.note': '💡 Note : Une fois déverrouillé, vous pouvez ouvrir votre PDF sans mot de passe.',
    'tool.image.size': 'Sélectionner la Taille du Papier :',
    'tool.image.a4': 'Taille A4',
    'tool.image.letter': 'Taille Lettre',
    'tool.image.fit': 'Ajustement Automatique',
    'tool.image.margin': 'Espace blanc autour des bords (Marges) :',
    'tool.image.margin_note': '💡 Réglez ceci sur 0 si vous voulez que vos images remplissent toute la page.',
    'tool.pdf2img.title': '📸 Extraire les images des pages',
    'tool.pdf2img.desc': 'Cette outil convertira instantanément chaque page en fichier image.',
    'tool.delete.which': 'Quels numéros de page souhaitez-vous supprimer ?',
    'tool.delete.placeholder': 'ex. 2, 4',
    'tool.delete.example': '💡 Exemple : Tapez 2, 4 pour effacer les pages 2 et 4.',
    'tool.extract.which': 'Quelles pages souhaitez-vous conserver comme nouveau fichier ?',
    'tool.extract.placeholder': 'ex. 1, 3, 5',
    'tool.extract.how': '💡 Comment ça marche : Tapez les pages que vous voulez garder. Cela crée un nouveau PDF.',
    'tool.watermark.type': 'Tapez le Texte de votre Filigrane :',
    'tool.watermark.placeholder': 'ex. BROUILLON, COPIA',
    'tool.watermark.size': 'Taille du Texte :',
    'tool.watermark.opacity': 'Niveau de transparence (Opacité) :',
    'tool.watermark.color': 'Choisir la Couleur du Texte :',
    'tool.watermark.rotation': 'Angle d inclinaison (Rotation) :',
    'tool.watermark.note': '💡 Une opacité de 0.2 est très claire et délavée. 1.0 est unie.',
    'tool.page_num.how': 'À quoi doivent ressembler les numéros de page ?',
    'tool.page_num.placeholder': 'ex. Page {n} sur {total}',
    'tool.page_num.hint': '💡 Astuce : {n} indique le numéro de la page, et {total} affiche le total des pages.',
    'tool.page_num.placement': 'Alignement de Placement :',
    'tool.page_num.bottom_center': 'En Bas au Centre',
    'tool.page_num.bottom_right': 'Coin Inférieur Droit',
    'tool.page_num.bottom_left': 'Coin Inférieur Gauche',
    'tool.page_num.top_center': 'En Haut au Centre',
    'tool.page_num.top_right': 'Coin Supérieur Droit',
    'cookie.text': 'Nous utilisons des cookies tiers (tels que Google AdSense) pour diffuser des annonces de sponsors qui aident à garder cet utilitaire Web 100% gratuit. Vos fichiers PDF sont traités entièrement dans votre navigateur local et sont totalement à l abri des téléchargements sur le serveur.',
    'tools.extract-pages.name': 'Extraire des pages'
  }
};

for (const lang in additions) {
  if (content.includes(`  ${lang}: {`)) {
    let toAdd = '';
    for (const key in additions[lang]) {
      toAdd += `    "${key}": "${additions[lang][key]}",\n`;
    }
    content = content.replace(`  ${lang}: {`, `  ${lang}: {\n${toAdd}`);
  }
}

fs.writeFileSync('src/data/translations.ts', content);
console.log("Updated translations.ts successfully");
