const fs = require('fs');
let content = fs.readFileSync('src/data/translations.ts', 'utf8');

const replacements = {
  "en": `"privacy.doc_title": "Privacy Policy",
    "privacy.intro": "TacoPDF is fully committed to your privacy and data security. As a provider of free online PDF tools, we pioneer a local processing (Client-Side) architecture to guarantee maximum document protection. This Privacy Policy outlines how we protect your data when you use our services.",
    "privacy.p1.title": "1. 100% Local Processing (No Server Uploads)",
    "privacy.p1.text": "All file manipulations (such as Merge PDF, Split PDF, and other conversion formats) are processed exclusively within your device's browser memory using modern WebAssembly and JavaScript technologies. We never upload, store, read, or distribute your documents. Your PDF files never once touch or pass through TacoPDF servers. The confidentiality of your documents rests entirely in your hands.",
    "privacy.p2.title": "2. Use of Cookies & Local Preferences",
    "privacy.p2.text": "To provide a seamless and responsive user experience (UX), TacoPDF utilizes basic cookies stored in your browser. These cookies are extremely small and are solely responsible for saving your tool interface preferences (such as language selection or display settings). By continuing to use our services, you consent to the use of these essential cookies for your navigational convenience.",
    "privacy.p3.title": "3. Third-Party Advertising",
    "privacy.p3.text": "In order to continue providing these high-performance PDF services for free to the public, TacoPDF displays sponsored advertisements. Third-party vendors, including Google, use advertising cookies to serve ads based on your prior visits to this website or other websites on the internet. Google's use of advertising cookies enables it and its partners to serve ads that are most relevant to users to support the maintenance of our infrastructure.",
    "privacy.p4.title": "4. Control & Opt-out of Personalized Advertising",
    "privacy.p4.text": "You have full control over your advertising privacy. Users may opt-out of personalized advertising at any time by visiting <a href=\\"https://myadcenter.google.com/\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">Google Ads Settings</a>. Alternatively, you may also disable the use of cookies for interest-based advertising by third-party vendors via the <a href=\\"https://www.aboutads.info\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">www.aboutads.info</a> website.",
    "privacy.p5.title": "5. Web Analytics and Log Files",
    "privacy.p5.text": "To ensure the website runs stably and continues to improve, we collect standard traffic analytics data. This data includes basic information such as browser type, time of visit, tool pages accessed, and anonymized IP addresses. It is strictly noted that this tracking is purely limited to web page interactions and absolutely does not track, collect, or have access to the contents of the PDF documents that you process locally on your device.",
    "privacy.p6.title": "6. Donations and Third-Party Payment Processing",
    "privacy.p6.text": "To support our operational costs and infrastructure development, TacoPDF accepts voluntary donations from users. The donation transaction process is handled entirely by secure third-party platforms, namely Saweria (for the Indonesian region) and Ko-Fi (for international).<br><br>TacoPDF never requests, processes, or stores your sensitive financial information (such as credit card numbers or banking details) on our servers. Any form of data you provide when making a donation transaction (such as name or email address) is governed by the Privacy Policy of the respective payment service providers.",
    "privacy.p7.title": "7. Contact the Support Team",
    "privacy.p7.text": "Your trust is our top priority. If you have any further questions, feedback, or concerns regarding these privacy protection practices, please contact our team at any time via the <a href=\\"/en/contact\\" class=\\"text-primary underline\\">Contact Support</a> page."`,
    
  "es": `"privacy.doc_title": "Política de Privacidad",
    "privacy.intro": "TacoPDF está plenamente comprometido con su privacidad y la seguridad de sus datos. Como proveedor de herramientas PDF en línea gratuitas, somos pioneros en una arquitectura de procesamiento local (Client-Side) para garantizar la máxima protección de los documentos. Esta Política de Privacidad describe cómo protegemos sus datos cuando utiliza nuestros servicios.",
    "privacy.p1.title": "1. Procesamiento 100% Local (Sin Cargas al Servidor)",
    "privacy.p1.text": "Todas las manipulaciones de archivos (como Unir PDF, Dividir PDF y otros formatos de conversión) se procesan exclusivamente dentro de la memoria del navegador en su dispositivo utilizando tecnologías modernas de WebAssembly y JavaScript. Nunca cargamos, almacenamos, leemos ni distribuimos sus documentos. Sus archivos PDF nunca tocan ni pasan por los servidores de TacoPDF. La confidencialidad de sus documentos está enteramente en sus manos.",
    "privacy.p2.title": "2. Uso de Cookies y Preferencias Locales",
    "privacy.p2.text": "Para ofrecer una experiencia de usuario (UX) fluida y receptiva, TacoPDF utiliza cookies básicas almacenadas en su navegador. Estas cookies son extremadamente pequeñas y solo tienen la función de guardar las preferencias de interfaz de su herramienta (como la selección de idioma o la configuración de pantalla). Al continuar utilizando nuestros servicios, usted acepta el uso de estas cookies esenciales para la comodidad de su navegación.",
    "privacy.p3.title": "3. Publicidad de Terceros",
    "privacy.p3.text": "Para poder seguir ofreciendo estos servicios PDF de alto rendimiento de forma gratuita al público, TacoPDF muestra anuncios patrocinados. Los proveedores externos, incluido Google, utilizan cookies de publicidad para publicar anuncios basados en sus visitas anteriores a este sitio web u otros sitios web en Internet. El uso de cookies publicitarias por parte de Google permite a Google y a sus socios publicar los anuncios más relevantes para los usuarios con el fin de respaldar el mantenimiento de nuestra infraestructura.",
    "privacy.p4.title": "4. Control y Exclusión (Opt-out) de la Publicidad Personalizada",
    "privacy.p4.text": "Usted tiene control total sobre su privacidad publicitaria. Los usuarios pueden excluirse (opt-out) de la publicidad personalizada en cualquier momento visitando la <a href=\\"https://myadcenter.google.com/\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">Configuración de Anuncios de Google</a>. Alternativamente, también puede desactivar el uso de cookies por parte de proveedores externos para publicidad basada en intereses a través del sitio web <a href=\\"https://www.aboutads.info\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">www.aboutads.info</a>.",
    "privacy.p5.title": "5. Analítica Web y Archivos de Registro",
    "privacy.p5.text": "Para garantizar que el sitio web funcione de manera estable y continúe desarrollándose, recopilamos datos analíticos de tráfico estándar. Estos datos incluyen información básica como el tipo de navegador, la hora de la visita, las páginas de herramientas a las que se accedió y las direcciones IP anonimizadas. Es muy importante tener en cuenta que este seguimiento se limita puramente a las interacciones de la página web y de ninguna manera rastrea, recopila ni tiene acceso al contenido de los documentos PDF que usted procesa localmente en su dispositivo.",
    "privacy.p6.title": "6. Donaciones y Procesamiento de Pagos de Terceros",
    "privacy.p6.text": "Para apoyar nuestros costos operativos y el desarrollo de infraestructura, TacoPDF acepta donaciones voluntarias de los usuarios. El proceso de transacción de donaciones es manejado en su totalidad por plataformas seguras de terceros, a saber, Saweria (para la región de Indonesia) y Ko-Fi (para nivel internacional).<br><br>TacoPDF nunca solicita, procesa ni almacena su información financiera confidencial (como números de tarjetas de crédito o datos bancarios) en nuestros servidores. Cualquier forma de datos que usted proporcione al realizar una transacción de donación (como nombre o dirección de correo electrónico) se rige por la Política de Privacidad de los respectivos proveedores de servicios de pago.",
    "privacy.p7.title": "7. Contactar al Equipo de Soporte",
    "privacy.p7.text": "Su confianza es nuestra principal prioridad. Si tiene más preguntas, comentarios o inquietudes con respecto a estas prácticas de protección de la privacidad, comuníquese con nuestro equipo en cualquier momento a través de la página de <a href=\\"/es/contact\\" class=\\"text-primary underline\\">Contactar Soporte</a>."`,

  "fr": `"privacy.doc_title": "Politique de Confidentialité",
    "privacy.intro": "TacoPDF s'engage pleinement à respecter votre confidentialité et la sécurité de vos données. En tant que fournisseur d'outils PDF en ligne gratuits, nous sommes pionniers d'une architecture de traitement local (Client-Side) pour garantir une protection maximale des documents. La présente Politique de Confidentialité décrit comment nous protégeons vos données lorsque vous utilisez nos services.",
    "privacy.p1.title": "1. Traitement 100 % Local (Aucun Téléversement sur Serveur)",
    "privacy.p1.text": "Toutes les manipulations de fichiers (telles que Fusionner PDF, Diviser PDF et d'autres formats de conversion) sont traitées exclusivement dans la mémoire du navigateur de votre appareil à l'aide de technologies modernes WebAssembly et JavaScript. Nous ne téléversons, ne stockons, ne lisons ni ne distribuons jamais vos documents. Vos fichiers PDF ne touchent ni ne transitent jamais par les serveurs de TacoPDF. La confidentialité de vos documents est entièrement entre vos mains.",
    "privacy.p2.title": "2. Utilisation de Cookies et Préférences Locales",
    "privacy.p2.text": "Pour offrir une expérience utilisateur (UX) fluide et réactive, TacoPDF utilise des cookies de base stockés dans votre navigateur. Ces cookies sont extrêmement petits et ont pour seule fonction de sauvegarder les préférences de l'interface de votre outil (telles que le choix de la langue ou les paramètres d'affichage). En continuant à utiliser nos services, vous consentez à l'utilisation de ces cookies essentiels pour le confort de votre navigation.",
    "privacy.p3.title": "3. Publicité de Tiers",
    "privacy.p3.text": "Afin de pouvoir continuer à fournir gratuitement ces services PDF de haute performance au public, TacoPDF affiche des annonces sponsorisées. Des fournisseurs tiers, y compris Google, utilisent des cookies publicitaires pour diffuser des annonces en fonction de vos visites antérieures sur ce site Web ou d'autres sites Web sur Internet. L'utilisation de cookies publicitaires par Google permet à Google et à ses partenaires de diffuser des annonces les plus pertinentes pour les utilisateurs afin de soutenir la maintenance de notre infrastructure.",
    "privacy.p4.title": "4. Contrôle et Désactivation (Opt-out) de la Publicité Personnalisée",
    "privacy.p4.text": "Vous avez un contrôle total sur votre confidentialité publicitaire. Les utilisateurs peuvent se désinscrire (opt-out) de la publicité personnalisée à tout moment en visitant les <a href=\\"https://myadcenter.google.com/\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">Paramètres des annonces Google</a>. Alternativement, vous pouvez également désactiver l'utilisation de cookies par des fournisseurs tiers pour la publicité ciblée par centres d'intérêt via le site Web <a href=\\"https://www.aboutads.info\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">www.aboutads.info</a>.",
    "privacy.p5.title": "5. Analyse Web et Fichiers Journaux",
    "privacy.p5.text": "Pour s'assurer que le site Web fonctionne de manière stable et continue de se développer, nous collectons des données analytiques de trafic standard. Ces données comprennent des informations de base telles que le type de navigateur, l'heure de la visite, les pages d'outils consultées et les adresses IP anonymisées. Il est extrêmement important de noter que ce suivi est purement limité aux interactions des pages Web et qu'il ne suit, ne collecte ni n'a en aucun cas accès au contenu des documents PDF que vous traitez localement sur votre appareil.",
    "privacy.p6.title": "6. Dons et Traitement des Paiements par des Tiers",
    "privacy.p6.text": "Pour soutenir nos coûts opérationnels et le développement de notre infrastructure, TacoPDF accepte les dons volontaires des utilisateurs. Le processus de transaction des dons est entièrement géré par des plateformes tierces sécurisées, à savoir Saweria (pour la région indonésienne) et Ko-Fi (à l'international).<br><br>TacoPDF ne demande, ne traite ni ne stocke jamais vos informations financières sensibles (telles que les numéros de carte de crédit ou les coordonnées bancaires) sur nos serveurs. Toute forme de données que vous fournissez lors d'une transaction de don (telle que le nom ou l'adresse e-mail) est régie par la Politique de Confidentialité des fournisseurs de services de paiement respectifs.",
    "privacy.p7.title": "7. Contacter l'Équipe d'Assistance",
    "privacy.p7.text": "Votre confiance est notre priorité absolue. Si vous avez d'autres questions, des commentaires ou des préoccupations concernant ces pratiques de protection de la confidentialité, veuillez contacter notre équipe à tout moment via la page <a href=\\"/fr/contact\\" class=\\"text-primary underline\\">Contacter l'Assistance</a>."`,

  "de": `"privacy.doc_title": "Datenschutzerklärung",
    "privacy.intro": "TacoPDF verpflichtet sich in vollem Umfang dem Schutz Ihrer Privatsphäre und Ihrer Datensicherheit. Als Anbieter von kostenlosen Online-PDF-Tools sind wir Vorreiter bei einer lokalen Verarbeitungsarchitektur (Client-Side), um einen maximalen Dokumentenschutz zu gewährleisten. Diese Datenschutzrichtlinie beschreibt, wie wir Ihre Daten schützen, wenn Sie unsere Dienste nutzen.",
    "privacy.p1.title": "1. 100 % Lokale Verarbeitung (Kein Server-Upload)",
    "privacy.p1.text": "Alle Dateimanipulationen (wie PDF Zusammenfügen, PDF Teilen und andere Konvertierungsformate) werden ausschließlich im Arbeitsspeicher des Browsers auf Ihrem Gerät unter Verwendung moderner WebAssembly- und JavaScript-Technologien verarbeitet. Wir laden Ihre Dokumente niemals hoch, speichern, lesen oder verbreiten sie. Ihre PDF-Dateien berühren oder passieren niemals die Server von TacoPDF. Die Vertraulichkeit Ihrer Dokumente liegt vollständig in Ihren Händen.",
    "privacy.p2.title": "2. Verwendung von Cookies & Lokalen Präferenzen",
    "privacy.p2.text": "Um eine reibungslose und reaktionsschnelle Benutzeroberfläche (UX) zu bieten, verwendet TacoPDF grundlegende Cookies, die in Ihrem Browser gespeichert werden. Diese Cookies sind extrem klein und dienen ausschließlich dazu, die Schnittstellenpräferenzen Ihres Tools (wie Sprachauswahl oder Anzeigeeinstellungen) zu speichern. Durch die weitere Nutzung unserer Dienste stimmen Sie der Verwendung dieser wesentlichen Cookies für Ihren Navigationskomfort zu.",
    "privacy.p3.title": "3. Werbung Dritter",
    "privacy.p3.text": "Um diese leistungsstarken PDF-Dienste der Öffentlichkeit weiterhin kostenlos zur Verfügung stellen zu können, schaltet TacoPDF gesponserte Werbung. Drittanbieter, einschließlich Google, verwenden Werbe-Cookies, um Anzeigen basierend auf Ihren vorherigen Besuchen auf dieser Website oder anderen Websites im Internet zu schalten. Die Verwendung von Werbe-Cookies durch Google ermöglicht es Google und seinen Partnern, Anzeigen zu schalten, die für die Benutzer am relevantesten sind, um die Aufrechterhaltung unserer Infrastruktur zu unterstützen.",
    "privacy.p4.title": "4. Kontrolle & Abmeldung (Opt-out) von Personalisierter Werbung",
    "privacy.p4.text": "Sie haben die volle Kontrolle über Ihre Werbeprivatsphäre. Benutzer können sich jederzeit von personalisierter Werbung abmelden (Opt-out), indem sie die <a href=\\"https://myadcenter.google.com/\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">Google-Anzeigeneinstellungen</a> besuchen. Alternativ können Sie auch die Verwendung von Cookies durch Drittanbieter für interessenbezogene Werbung über die Website <a href=\\"https://www.aboutads.info\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">www.aboutads.info</a> deaktivieren.",
    "privacy.p5.title": "5. Webanalyse und Protokolldateien",
    "privacy.p5.text": "Um sicherzustellen, dass die Website stabil läuft und sich kontinuierlich weiterentwickelt, erfassen wir standardmäßige Traffic-Analysedaten. Diese Daten umfassen grundlegende Informationen wie Browsertyp, Besuchszeit, aufgerufene Tool-Seiten und anonymisierte IP-Adressen. Es ist äußerst wichtig zu beachten, dass sich dieses Tracking ausschließlich auf Webseiteninteraktionen beschränkt und den Inhalt der PDF-Dokumente, die Sie lokal auf Ihrem Gerät verarbeiten, in keiner Weise verfolgt, sammelt oder darauf zugreift.",
    "privacy.p6.title": "6. Spenden und Zahlungsabwicklung durch Dritte",
    "privacy.p6.text": "Um unsere Betriebskosten und die Infrastrukturentwicklung zu unterstützen, akzeptiert TacoPDF freiwillige Spenden von Benutzern. Der Spendentransaktionsprozess wird vollständig von sicheren Drittanbieter-Plattformen abgewickelt, nämlich Saweria (für die indonesische Region) und Ko-Fi (für den internationalen Bereich).<br><br>TacoPDF fragt niemals nach Ihren sensiblen Finanzinformationen (wie Kreditkartennummern oder Bankdaten), verarbeitet oder speichert diese auf unseren Servern. Jegliche Form von Daten, die Sie bei der Durchführung einer Spendentransaktion angeben (wie Name oder E-Mail-Adresse), unterliegen der Datenschutzrichtlinie der jeweiligen Zahlungsdienstleister.",
    "privacy.p7.title": "7. Kontakt zum Support-Team",
    "privacy.p7.text": "Ihr Vertrauen ist unsere oberste Priorität. Wenn Sie weitere Fragen, Feedback oder Bedenken bezüglich dieser Datenschutzpraktiken haben, wenden Sie sich bitte jederzeit über die Seite <a href=\\"/de/contact\\" class=\\"text-primary underline\\">Support Kontaktieren</a> an unser Team."`,

  "pt": `"privacy.doc_title": "Política de Privacidade",
    "privacy.intro": "A TacoPDF está totalmente comprometida com a sua privacidade e segurança de dados. Como um provedor de ferramentas de PDF online gratuitas, fomos pioneiros em uma arquitetura de processamento local (Client-Side) para garantir a máxima proteção de documentos. Esta Política de Privacidade descreve como protegemos seus dados quando você utiliza nossos serviços.",
    "privacy.p1.title": "1. Processamento 100% Local (Sem Uploads para o Servidor)",
    "privacy.p1.text": "Todas as manipulações de arquivos (como Juntar PDF, Dividir PDF e outros formatos de conversão) são processadas exclusivamente na memória do navegador em seu dispositivo, utilizando tecnologias modernas de WebAssembly e JavaScript. Nós nunca enviamos, armazenamos, lemos ou distribuímos seus documentos. Seus arquivos PDF nunca tocam ou passam pelos servidores da TacoPDF. A confidencialidade de seus documentos está inteiramente em suas mãos.",
    "privacy.p2.title": "2. Uso de Cookies e Preferências Locais",
    "privacy.p2.text": "Para oferecer uma experiência de usuário (UX) contínua e responsiva, a TacoPDF utiliza cookies básicos armazenados em seu navegador. Esses cookies são extremamente pequenos e têm a única função de salvar as preferências de interface de sua ferramenta (como seleção de idioma ou configurações de exibição). Ao continuar a utilizar nossos serviços, você consente com o uso desses cookies essenciais para a conveniência de sua navegação.",
    "privacy.p3.title": "3. Publicidade de Terceiros",
    "privacy.p3.text": "Para continuar fornecendo esses serviços de PDF de alto desempenho gratuitamente ao público, a TacoPDF exibe anúncios patrocinados. Fornecedores de terceiros, incluindo o Google, utilizam cookies de publicidade para veicular anúncios com base em suas visitas anteriores a este site ou a outros sites na internet. O uso de cookies de publicidade pelo Google permite que o Google e seus parceiros veiculem os anúncios mais relevantes para os usuários, a fim de apoiar a manutenção de nossa infraestrutura.",
    "privacy.p4.title": "4. Controle e Exclusão (Opt-out) de Publicidade Personalizada",
    "privacy.p4.text": "Você tem controle total sobre sua privacidade publicitária. Os usuários podem optar por não receber (opt-out) publicidade personalizada a qualquer momento visitando as <a href=\\"https://myadcenter.google.com/\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">Configurações de Anúncios do Google</a>. Alternativamente, você também pode desativar o uso de cookies por fornecedores de terceiros para publicidade baseada em interesses através do site <a href=\\"https://www.aboutads.info\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">www.aboutads.info</a>.",
    "privacy.p5.title": "5. Web Analytics e Arquivos de Log",
    "privacy.p5.text": "Para garantir que o site funcione de forma estável e continue a se desenvolver, coletamos dados padrão de análise de tráfego. Esses dados incluem informações básicas, como tipo de navegador, horário da visita, páginas de ferramentas acessadas e endereços IP anonimizados. É fundamental observar que este rastreamento é puramente limitado às interações da página da web e, de forma alguma, rastreia, coleta ou tem acesso ao conteúdo dos documentos PDF que você processa localmente em seu dispositivo.",
    "privacy.p6.title": "6. Doações e Processamento de Pagamentos de Terceiros",
    "privacy.p6.text": "Para apoiar nossos custos operacionais e o desenvolvimento de infraestrutura, a TacoPDF aceita doações voluntárias de usuários. O processo de transação de doações é tratado inteiramente por plataformas seguras de terceiros, a saber, Saweria (para a região da Indonésia) e Ko-Fi (para a área internacional).<br><br>A TacoPDF nunca solicita, processa ou armazena suas informações financeiras confidenciais (como números de cartão de crédito ou dados bancários) em nossos servidores. Qualquer forma de dado que você fornecer ao realizar uma transação de doação (como nome ou endereço de e-mail) é regida pela Política de Privacidade dos respectivos provedores de serviços de pagamento.",
    "privacy.p7.title": "7. Contatar a Equipe de Suporte",
    "privacy.p7.text": "Sua confiança é a nossa principal prioridade. Se você tiver mais perguntas, comentários ou preocupações sobre essas práticas de proteção de privacidade, entre em contato com nossa equipe a qualquer momento através da página de <a href=\\"/pt/contact\\" class=\\"text-primary underline\\">Contatar Suporte</a>."`,

  "ja": `"privacy.doc_title": "プライバシーポリシー",
    "privacy.intro": "TacoPDFは、お客様のプライバシーとデータセキュリティに全面的に取り組んでいます。無料のオンラインPDFツールのプロバイダーとして、弊社は文書の最大限の保護を保証するために、ローカル処理（Client-Side）アーキテクチャを先駆けて導入しています。本プライバシーポリシーでは、お客様が弊社のサービスをご利用になる際に、弊社がどのようにお客様のデータを保護するかを規定しています。",
    "privacy.p1.title": "1. 100%ローカル処理（サーバーへのアップロードなし）",
    "privacy.p1.text": "PDFの結合、PDFの分割、その他の変換フォーマットなどのすべてのファイル操作は、最新のWebAssemblyおよびJavaScriptテクノロジーを使用して、お客様のデバイス上のブラウザのメモリ内でのみ処理されます。弊社がお客様の文書をアップロード、保存、読み取り、または配布することは決してありません。お客様のPDFファイルがTacoPDFのサーバーに触れたり、通過したりすることは一度もありません。文書の機密性はお客様の手によって完全に守られています。",
    "privacy.p2.title": "2. Cookieの使用とローカル設定",
    "privacy.p2.text": "シームレスで応答性の高いユーザーエクスペリエンス（UX）を提供するために、TacoPDFはお客様のブラウザに保存される基本的なCookieを使用します。これらのCookieは非常に小さく、ツールのインターフェース設定（言語の選択や表示設定など）を保存する役割のみを果たします。弊社のサービスを継続して利用することにより、お客様はナビゲーションの利便性のためにこれらの必須のCookieを使用することに同意したものとみなされます。",
    "privacy.p3.title": "3. 第三者広告",
    "privacy.p3.text": "これらの高性能なPDFサービスを一般に無料で提供し続けるために、TacoPDFはスポンサー広告を表示しています。Googleを含む第三者ベンダーは、広告Cookieを使用して、当ウェブサイトまたはインターネット上の他のウェブサイトへのお客様の過去のアクセス情報に基づいて広告を配信します。Googleによる広告Cookieの使用により、Googleとそのパートナーは、インフラストラクチャの維持をサポートするために、ユーザーに最も関連性の高い広告を配信することができます。",
    "privacy.p4.title": "4. パーソナライズされた広告の管理とオプトアウト（Opt-out）",
    "privacy.p4.text": "お客様は広告に関するプライバシーを完全に管理できます。ユーザーは、<a href=\\"https://myadcenter.google.com/\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">Google 広告設定</a>にアクセスすることで、いつでもパーソナライズされた広告をオプトアウト（Opt-out）することができます。また、<a href=\\"https://www.aboutads.info\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">www.aboutads.info</a> のウェブサイトにアクセスして、第三者ベンダーによるインタレストベース広告のためのCookieの使用を無効にすることもできます。",
    "privacy.p5.title": "5. ウェブ分析とログファイル",
    "privacy.p5.text": "ウェブサイトが安定して動作し、継続的に発展するように、弊社は標準的なトラフィック分析データを収集します。このデータには、ブラウザの種類、訪問時間、アクセスしたツールページ、匿名化されたIPアドレスなどの基本的な情報が含まれます。この追跡はウェブページでのやり取りに純粋に限定されており、お客様がデバイス上でローカルに処理するPDF文書のコンテンツを追跡したり、収集したり、アクセスしたりすることは絶対にないことにご留意ください。",
    "privacy.p6.title": "6. 寄付および第三者の支払い処理",
    "privacy.p6.text": "運営コストとインフラストラクチャの開発をサポートするために、TacoPDFはユーザーからの自発的な寄付を受け付けています。寄付の取引処理は、Saweria（インドネシア地域向け）およびKo-Fi（国際向け）という安全な第三者プラットフォームによって完全に処理されます。<br><br>TacoPDFが、お客様の機密性の高い財務情報（クレジットカード番号や銀行の詳細など）を弊社のサーバーで要求、処理、または保存することは決してありません。寄付の取引を行う際にお客様が提供するあらゆる形式のデータ（名前やメールアドレスなど）は、それぞれの決済サービスプロバイダーのプライバシーポリシーによって管理されます。",
    "privacy.p7.title": "7. サポートチームへの問い合わせ",
    "privacy.p7.text": "お客様の信頼は弊社の最優先事項です。これらのプライバシー保護の慣行に関してご質問、ご意見、またはご懸念がある場合は、<a href=\\"/ja/contact\\" class=\\"text-primary underline\\">サポートへの問い合わせ</a>ページを通じていつでも弊社チームにお問い合わせください。"`,

  "id": `"privacy.doc_title": "Kebijakan Privasi",
    "privacy.intro": "TacoPDF berkomitmen penuh terhadap privasi dan keamanan data Anda. Sebagai penyedia alat PDF online gratis, kami memelopori arsitektur pemrosesan lokal (Client-Side) untuk menjamin perlindungan dokumen tingkat maksimal. Kebijakan Privasi ini menguraikan bagaimana kami melindungi data Anda saat Anda menggunakan layanan kami.",
    "privacy.p1.title": "1. Pemrosesan Lokal 100% (Tanpa Unggah ke Server)",
    "privacy.p1.text": "Semua manipulasi file (seperti Gabung PDF, Pisah PDF, dan format konversi lainnya) diproses secara eksklusif di dalam memori browser pada perangkat Anda menggunakan teknologi WebAssembly dan JavaScript modern. Kami tidak pernah mengunggah, menyimpan, membaca, atau mendistribusikan dokumen Anda. File PDF Anda tidak pernah sekalipun menyentuh atau melewati server TacoPDF. Kerahasiaan dokumen Anda berada sepenuhnya di tangan Anda.",
    "privacy.p2.title": "2. Penggunaan Cookie & Preferensi Lokal",
    "privacy.p2.text": "Untuk menyajikan pengalaman pengguna (UX) yang mulus dan responsif, TacoPDF menggunakan cookie dasar yang tersimpan di browser Anda. Cookie ini berukuran sangat kecil dan hanya bertugas menyimpan preferensi antarmuka alat Anda (seperti pilihan bahasa atau pengaturan layar). Dengan terus menggunakan layanan kami, Anda menyetujui penggunaan cookie esensial ini demi kenyamanan navigasi Anda.",
    "privacy.p3.title": "3. Iklan Pihak Ketiga",
    "privacy.p3.text": "Agar dapat terus menyediakan layanan PDF berkinerja tinggi ini secara gratis kepada publik, TacoPDF menampilkan iklan sponsor. Vendor pihak ketiga, termasuk Google, menggunakan cookie periklanan untuk menayangkan iklan berdasarkan kunjungan Anda sebelumnya ke situs web ini atau situs web lain di internet. Penggunaan cookie oleh Google memungkinkan Google dan mitranya menyajikan iklan yang paling relevan bagi pengguna untuk mendukung pemeliharaan infrastruktur kami.",
    "privacy.p4.title": "4. Kontrol & Penyisihan Iklan yang Dipersonalisasi",
    "privacy.p4.text": "Anda memiliki kendali penuh atas privasi periklanan Anda. Pengguna dapat menyisih (opt-out) dari iklan hasil personalisasi kapan saja dengan mengunjungi <a href=\\"https://myadcenter.google.com/\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">Setelan Iklan Google</a>. Sebagai alternatif, Anda juga dapat menonaktifkan penggunaan cookie oleh vendor pihak ketiga untuk iklan berbasis minat melalui situs <a href=\\"https://www.aboutads.info\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"text-primary underline\\">www.aboutads.info</a>.",
    "privacy.p5.title": "5. Analisis Web dan File Log",
    "privacy.p5.text": "Untuk memastikan situs web berjalan dengan stabil dan terus berkembang, kami mengumpulkan data analitik lalu lintas standar. Data ini mencakup informasi dasar seperti jenis browser, waktu kunjungan, halaman alat yang diakses, dan alamat IP yang telah dianonimkan. Sangat penting dicatat bahwa pelacakan ini murni terbatas pada interaksi halaman web, dan sama sekali tidak melacak, mengumpulkan, atau memiliki akses ke isi dokumen PDF yang Anda proses secara lokal di perangkat Anda.",
    "privacy.p6.title": "6. Donasi dan Pemrosesan Pembayaran Pihak Ketiga",
    "privacy.p6.text": "Untuk mendukung biaya operasional dan pengembangan infrastruktur kami, TacoPDF menerima donasi sukarela dari pengguna. Proses transaksi donasi ditangani sepenuhnya oleh platform pihak ketiga yang aman, yaitu Saweria (untuk wilayah Indonesia) dan Ko-Fi (untuk internasional).<br><br>TacoPDF tidak pernah meminta, memproses, atau menyimpan informasi keuangan sensitif Anda (seperti nomor kartu kredit atau detail perbankan) di server kami. Segala bentuk data yang Anda berikan saat melakukan transaksi donasi (seperti nama atau alamat email) diatur oleh Kebijakan Privasi dari masing-masing penyedia layanan pembayaran tersebut.",
    "privacy.p7.title": "7. Hubungi Tim Dukungan",
    "privacy.p7.text": "Kepercayaan Anda adalah prioritas utama kami. Jika Anda memiliki pertanyaan lebih lanjut, masukan, atau kekhawatiran mengenai praktik perlindungan privasi ini, silakan hubungi tim kami kapan saja melalui halaman <a href=\\"/id/contact\\" class=\\"text-primary underline\\">Hubungi Dukungan</a>."`
};

for (const lang of Object.keys(replacements)) {
  const langKey = '"' + lang + '": {';
  const langKeyIndex = content.indexOf(langKey);
  const privacyStart = content.indexOf('"privacy.doc_title":', langKeyIndex);
  let nextKey = content.indexOf('"contact.back":', privacyStart);
  if (nextKey === -1) nextKey = content.indexOf('"workspace.preview.close_hint_mobile":', privacyStart); // DE case
  
  if (privacyStart !== -1 && nextKey !== -1) {
    const startIdx = content.lastIndexOf('\\n', privacyStart) + 1;
    const endIdx = content.lastIndexOf('\\n', nextKey);
    
    const blockToReplace = content.substring(startIdx, endIdx);
    content = content.replace(blockToReplace, replacements[lang] + '\\n\\n');
  }
}

fs.writeFileSync('src/data/translations.ts', content, 'utf8');
